import { pizzas } from "@/data";
import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React, { useState } from "react";

export const getStaticProps = async () => {
  const res = await fetch("http://localhost:1111/users");
  const data = await res.json();

  return {
    props: { api: data },
  };
};

const Amigo = ({ api }) => {
  return (
    <div>
      <Head>
        <title>Create Next App | CRUD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="cards">
        <div className="container1">
          <div className="ada">
            {api?.map((el) => {
              return (
                <div key={el?._id} className="card">
                  <img src={el?.image} alt="" />
                  <div className="content">
                    <h1>{el?.name}</h1>
                    <p>{el?.email.slice(0,200)}</p>
                    <button>Подробнее</button>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Amigo;
